services:
  - type: web
    name: api_petshop
    runtime: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: MONGO_URI
        sync: false

#     - key: JWT_SECRET 
#       sync: false generateValue: true
#     - key: JWT_EXPIRESIN
#       value: 1d
#     - key: BCRYPT_SALT_ROUNDS
#       value: 10